prep-javascript-variables Ignacio-Dominguez-Moral
Ignacio-Dominguez-Moral/prep-1122-code-solutions pull request #10
Opened 2022-11-22 20:04 UTC by Ignacio-Dominguez-Moral

![prep-javascript-variables](https://user-images.githubusercontent.com/115427465/203410526-dd8648de-0231-463c-80f4-08030385038f.PNG)

2022-11-22 22:09 UTC, thebearingedge requested changes

2022-11-22 22:09 UTC, thebearingedge commented on prep-javascript-variables/index.html
> +    var nothing = 'null';
For numbers, booleans, and null, we'll want to leave off the quotes so that the javascript engine doesn't interpret them as strings

2022-11-22 22:48 UTC, Ignacio-Dominguez-Moral commented
![image](https://user-images.githubusercontent.com/115427465/203436849-23212b1a-4feb-4743-b735-bdb97f6ed1b0.png)

2022-11-23 02:11 UTC, thebearingedge approved these changes

2022-11-23 02:14 UTC, merged